### ISSUE TITLE
[Test Case Results] iAccel

### ISSUE THREAD

**Issue by iAccel** [rlguy/Blender-FLIP-Fluids-Beta#104]
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749434/test_case_viscous_net65.zip)

There was a slight hiccup and it gave me a permission error, but after resuming the bake it was able to finish in no time. Let me know if you need more test cases. I will be running another on my home PC later today.

**Comment by rlguy** [comment]
Thanks!

Let me know if you run into any more permission errors. And if you are able to screenshot the error message, or see any errors in the Blender system console, please upload those.

I checked your results and it looks like the test ran okay, but you are affected by issue #7. This issue has been fixed in the most recent beta addon (**v0.1.2b**) and is included in the very recently uploaded version of the test suite addon (**v0.1.2t**).

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
