### ISSUE TITLE
[Test Case Results] Blaast

### ISSUE THREAD

**Issue by Blaast** [rlguy/Blender-FLIP-Fluids-Beta#110]
Hi ! Thanks for allowing me to test too !

Every test until now ran fine :
Currently running tests cases, first one is done, some other ones on the way, I will test on Athlon and FX tomorrow probably, and in the next days on my other systems (X5650 and L5640, maybe on the some servers too)

Already issued and answered, but I was surprised by the low usage of CPU and GPU, as here :  
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/issues/85
![report1](https://user-images.githubusercontent.com/19172543/36563224-bd4f38d6-1819-11e8-91ae-6a15a022ea82.JPG)
> I will test in higher resolution to see if there is a change in overall CPU/GPU usage
> Nice thing, it allows me to play and bake at the same time

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749482/test_case_cascading_water_feature100.zip)
> On HDD, 2x E5-2670, 1080+Titan, 57GB
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749597/test_case_lighthouse125.zip)
> On SSD, 2x E5-2670, 1080+Titan, 57GB

Q : would it be more interesting for FLIP fluid to invest in a faster single core performance based computer ? (or should I ask it in another issue instead of multiplying it here ?)

Best regards,
Blaast

**Comment by rlguy** [comment]
Thanks Blaast!

I checked your results and it looks like the test ran without errors.

In the the first wave of testing, I have noticed that test results from Xeon hardware have been running on the slow side. We invited a second wave of testers with a focus on users with Intel Xeon CPU models so that we can collect more data and better optimize the simulator for a higher level of multithreading.

At the moment, the simulator is running much faster on fast single core performance systems.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by Blaast** [comment]
Added information : I'm currently running Lighthouse (not lite) at 500, CPU and GPU usage have increased, as expected, during the same kind of spikes as in low res and same as we can see in Elbeem/Manataflow. I though until then it was disk cache r/w speed related.  I guess it will be necessary for intensive simulations to get an 8th gen i5 (or even i3).

**Comment by Blaast** [comment]
I wanted to run a test on the AIIX4, but I got this error :
![screenshot 1](https://user-images.githubusercontent.com/19172543/36597124-68b9a11e-18a8-11e8-905b-64f72783cdcb.png)
![screenshot 2](https://user-images.githubusercontent.com/19172543/36597120-684a3e1e-18a8-11e8-991b-05204bdb7bfc.png)
![screenshot 3](https://user-images.githubusercontent.com/19172543/36597121-68699052-18a8-11e8-81f0-8a5e922f9ee8.png)
![screenshot 4](https://user-images.githubusercontent.com/19172543/36597122-68858dc0-18a8-11e8-9057-2b16b3844cc4.png)
![screenshot 5](https://user-images.githubusercontent.com/19172543/36597123-689f73b6-18a8-11e8-82ef-961516d8deac.png)

Haven't the time to dig it in, but it is either related to the network storage or something else.
> I have to test using it in local (WIP)
I'll keep running tests on my different computers the next days

**Comment by rlguy** [comment]
Some testers have reported encountering these errors after clicking the _Run Test Case_ button. This error means that the addon was not able to load the fluid engine library. So far, 100% of these cases have been solved by reinstalling/updating graphics drivers (see issue [#6](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/issues/6)). Please let me know if this fixes the issue.

**Comment by Blaast** [comment]
Testing it tomorrow !
One issue, not sure is has been reported, is a wobbly effect on an inflow :
capture of the issue : https://drive.google.com/open?id=1ejAABbsmGIuHCefU3e0eEDy37WWfh9Xt
I think it is related to world size (50m), if more file required
.blend : https://drive.google.com/open?id=1RdhlU1zLnDAovKe--2bNIejE78DIGXHi

**Comment by Blaast** [comment]
Pretty huge bug here : https://drive.google.com/open?id=1wUxMArl6bPNPd5SdufSQF1gY5VAHb-nj
.blend coming soon

**Comment by rlguy** [comment]
> As it had only an integrated GPU, I tried installed an old FX 1800 => Same error, even having installed latests drivers.
Does FLIP requires recent GPU ?
Would it work if I installed full version, instead of test version ?

Hey would you be able to to attach your system info for this computer? (Blender > Help > Save System Info)

I'll check to see if the GPU is compatible.

> Pretty huge bug here : https://drive.google.com/open?id=1wUxMArl6bPNPd5SdufSQF1gY5VAHb-nj
.blend coming soon

I checked the .blend file. It looks like a problem with your meshes. The simulator requires that object meshes be [manifold](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Manifold-Meshes). The meshes that are used as obstacle objects are non-manifold and this causes problems for the simulator.

Also, next time you run into a scene bug like this, please create a new issue to report it. It will make it easier for us to keep track of, and also more visible to other testers that may be having similar problems. Thanks!

**Comment by Blaast** [comment]
Sorry, I've been unexpectedly busy then away for some time ^^'

Well, long story but I had to uninstall GPU. GPU is old (2009), could have been something about it.
In short : AMD Athlon II x4 540, 4GB Ram, Old Nvidia Quadro FX 1800, W10 x64.
Maybe I shoud have tried to see about disabling GPU. Will try tonight (GMT+1)
I've had the previously quoted bug even after fixing non manifold objects. And with a clean scene but around he same setup (cube domain, 10% of it is liquid and abjects (cubes) falling inside.
I'm wondering if it could be related to rigid bodies (but I doubt so).
I keep trying, anyway. I think I will reinstall plugin to see if it solves the problem.
