### ISSUE TITLE
[Feature Request] Emit fluid from normal?

### ISSUE THREAD

**Issue by SimonCDalzell** [rlguy/Blender-FLIP-Fluids-Beta#130]
Is there a way to emit fluid from the normal of an object, rather than in a worldspace direction?

I can sort of get that effect by creating a "target" object, constraining the inflow object to the target with Track To, and setting the Inflow mode to Target, however this is a bit convoluted and requires that I precisely position the target object, which isn't ideal. Sorry if this has already been covered somewhere in the docs.

**Comment by rlguy** [comment]
Hey, I have a question about this feature:

Should the simulator emit fluid in the direction of all of the objects normals? For example, a sphere would emit fluid outwards in all directions.

Or should the simulator emit in the direction of a single normal? For example, the user would select a face and the inflow would emit all fluid in the direction of that face normal.

**Comment by SimonCDalzell** [comment]
That's a good question that I'm probably not qualified to answer :D

Is it currently possible to make an object emit in all directions? I was thinking of using it to emit from a single face.

**Comment by rlguy** [comment]
Hey,

At the moment it's not possible to make an object emit in all directions, but if this feature is wanted it could be added.

Now I have a question about this:

> I was thinking of using it to emit from a single face

I was assuming before that you were suggesting the entire inflow object volume to emit fluid in the direction of a single face. But does this mean that you want fluid to be only emitted at the location of a face instead of the entire inflow volume?

Sorry for all the questions! I just have to ask to make sure I understand exactly what feature is being requested.

**Comment by SimonCDalzell** [comment]
No problem at all! Sorry I'm not more clear, I think I need a better understanding of how fluid sims work to answer properly.

Real quick here's my understanding of it. It seems something like every frame, the volume taken up by the inflow object is converted to a fluid and moved in the direction set by the Manual or Target velocities. The space between the last volume and the newest volume is then filled in with fluid. It also looks kind of like this is what's happening when baking. Rather than a constant stream of fluid, there seem to be chunks the same size as the inflow object that get added each frame. Is that roughly correct?

If the inflow having volume is integral to how baking happens, I don't see how you could emit from a single face, unless you took the inflow volume and positioned it relative to that face for each frame or something?

**Comment by rlguy** [comment]
> Real quick here's my understanding of it. It seems something like every frame, the volume taken up by the inflow object is converted to a fluid and moved in the direction set by the Manual or Target velocities. The space between the last volume and the newest volume is then filled in with fluid. It also looks kind of like this is what's happening when baking. Rather than a constant stream of fluid, there seem to be chunks the same size as the inflow object that get added each frame. Is that roughly correct?

Yep, this is all correct!

> If the inflow having volume is integral to how baking happens, I don't see how you could emit from a single face, unless you took the inflow volume and positioned it relative to that face for each frame or something?

Yes, because of the way the simulator is implemented, there needs to be volume to the inflow to generate fluid.

**Comment by SimonCDalzell** [comment]
Hah! That I got any of that right is a huge surprise.

Given the above I think the easiest solution would be a "worldspace/local space" toggle, or just some way to emit relative to the orientation of the inflow. I'm thinking of situations where your inflow moves around a lot, like for simulating a firehose or something. Is there already an easy way to achieve this or am I talking rubbish? I assume the simulation will act funny if you move the inflow too quickly, but it should still be possible to simulate this kind of thing right?

**Comment by rlguy** [comment]
Hey SimonCDalzell,

I think that the better way to achieve this is to use the simulation features that already exist instead of adding another setting to the UI.

I would create a target object for the inflow and parent the target to the inflow object so that it follows the orientation of the inflow.

For an inflow object that moves around a lot, you may want to look into the [Add Object Velocity to Inflow](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Inflow-Object-Settings) option. Enabling this option creates more realistic inflows where the the emitted fluid has added velocity related to how fast the inflow object is moving.

Let me know if this answers your questions! I'll be closing this issue now.
