### ISSUE TITLE
[Bug/Error/Feature Request] Beer Foam Test

### ISSUE THREAD

**Issue by guilliamPL** [rlguy/Blender-FLIP-Fluids-Beta#146]
Hi,
I'm trying to simulate a mug filling with a beer. 
1) How to achieve more and much thicker foam? It's very characteristic for fluids with a lot of gas like a beer or coke. Maybe you should add additional option to generate a foam over the time on top of the surface?
2) Also after inflow is disabled fluid starts to disappear from the mug. I noticed in frame#158 strange drop of fluid outside the mug. Can someone simulate attached blend file and check this?
3) I think it will be nice to add variance parameter for Drag Coefficent of Bubbles.
4) Is there any way to control the amount of created Foam, Bubbles, Spray separately?
5) Blend file here:  [BeerFoamTest.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1754760/BeerFoamTest.zip)
6) Preview video https://youtu.be/UJRK9eDVh-M

**Comment by TripleDots** [comment]
The settings didn't transfer so I can't see what you did. But did you tick "preserve foam" in "whitewater?"

**Comment by guilliamPL** [comment]
Is there any way to send blend file with the used simulation settings?

**Comment by rlguy** [comment]
Hey guilliamPL,

The .blend file is working for me and includes your simulation settings.

In general, this type of small scale simulation is difficult for this simulator to handle.

**How to achieve more and much thicker foam? It's very characteristic for fluids with a lot of gas like a beer or coke. Maybe you should add additional option to generate a foam over the time on top of the surface?**

The foam feature works best for large scale whitewater effects (rivers/oceans). You may have trouble generating volumetric foam in this whitewater simulator. The whitewater simulator is not able to keep a particle separation between foam particles to create a thick foam layer.

**Also after inflow is disabled fluid starts to disappear from the mug. I noticed in frame#158 strange drop of fluid outside the mug. Can someone simulate attached blend file and check this?**

This may be an issue with volume loss. Volume loss is a problem inherent to FLIP simulators. Over time, mass in FLIP simulations tends to decrease. Since this is a small scale simulation, the fluid is moving relatively very fast, and this makes the volume loss more noticeable. I checked the .blend and the fluid is moving fast enough that it requires 10+ timesteps per frame. This is quite a lot, and after all those those substeps, volume loss will be quite noticeable.

The simulation could work better, and also run much faster, if you ran it in slow motion instead of real-time, but this may not be the kind of animation/effect that you want.

**I think it will be nice to add variance parameter for Drag Coefficent of Bubbles.**

I think this is a good idea. I think it would also be good to add a variance to the _Buoyancy Coefficent_. I have opened a feature request here: #159

**Is there any way to control the amount of created Foam, Bubbles, Spray separately?**

There isn't a direct way to specify the amount of each whitewater type. Whitewater particles are simulated in a life cycle: bubble particles float up and become foam, spray falls down and become foam, foam moves along the fluid surface.

Bubble particles are generated underwater in areas of high turbulence. The rate of bubble particle generation can be controlled with the _Turbulence Emission Rate_ setting. Since bubble rise up and become foam, altering this setting will also alter the amount of foam in the near future.

Foam/Spray particles are spawned at wavecrests. The rate of these generated particles can be controlled with the _Wavecrest Emission Rate_. Whether a particle is generated as a foam or spray particle depend on the motion of the fluid and location of the generated particle.

***

I hope this answers your questions! I am sorry that this may not be the perfect simulator for creating the simulation you are trying to achieve.
