### ISSUE TITLE
Unwanted movement of still standing tank and render artifacts with all objects that aren't 90 degrees straight

### ISSUE THREAD

**Issue by TripleDots** [rlguy/Blender-FLIP-Fluids-Beta#154]
**Issue 1** 

There is often a lot of unwanted movement. I noticed this first with higher viscosity (20) as with a lower one, while it happens, is not much of an issue.

**Issue 2**
With rendering all objects that do not look like a tube you get these rendering artifacts. (which is probably caused by the same bug as https://github.com/rlguy/Blender-FLIP-Fluids-Beta/issues/1)

Both are repeatable  in every scene I made and it happens on both CPU and GPU. 
I also tested it on 0.1.1b and 0.1.2b (still same results) but the full renders in the video are 0.1.2b.

Video:
https://gfycat.com/ReadyDirtyFoxterrier

**Comment by rlguy** [comment]
Hey TripleDots thanks for reporting these and for including a helpful video!

**Issue 1**

This is caused by how the simulator 'solves' the fluid equations. The simulator isn't able to calculate an exact solution to the fluid physics equations, it can only make a very good guess. The movement is caused by numerical differences between the 'solved' approximation and a theoretical exact solution. This is more noticeable in slower moving simulations, such as those with visosity.

The solver may be able to compute a better solution if you allow it take more calculation substeps. This can be done by increasing the 'Min Time Steps' value in the [FLIP Fluid Advanced](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Advanced-Settings) panel, but this will take more time to compute and may not improve the solution by a beneficial amount.

**Issue 2**

I have opened an improvement issue to fix this (issue #158). The issue also contains some workarounds.
