### ISSUE TITLE
Install Error: 'ImportError: DLL load failed: %1 is not a valid Win32 application.'

### ISSUE THREAD

**Issue by AlbinSjoegren** [rlguy/Blender-FLIP-Fluids-Beta#156]
# I have no idear of what is wrong but i made sure both my system and my blender verion is 64-bit
![20180226_172714](https://user-images.githubusercontent.com/23136737/36682420-58fde666-1b1b-11e8-90c0-c7320f0f741d.jpg)
![2018-02-26](https://user-images.githubusercontent.com/23136737/36682497-88fbeade-1b1b-11e8-981b-7434b52c4ed8.png)
![2018-02-26 1](https://user-images.githubusercontent.com/23136737/36682541-a39501f0-1b1b-11e8-97bc-a9ba5ee5715c.png)
# i have the same probelm when i try changing theme 
![2018-02-26 2](https://user-images.githubusercontent.com/23136737/36682986-ba4702d0-1b1c-11e8-993a-2fd4ffa09c49.png) 
@rlguy

**Comment by AlbinSjoegren** [comment]
![2018-02-26](https://user-images.githubusercontent.com/23136737/36682497-88fbeade-1b1b-11e8-981b-7434b52c4ed8.png)

**Comment by AlbinSjoegren** [comment]
![2018-02-26 1](https://user-images.githubusercontent.com/23136737/36682541-a39501f0-1b1b-11e8-97bc-a9ba5ee5715c.png)

**Comment by AlbinSjoegren** [comment]
i have the same probelm when i try changing theme 
![2018-02-26 2](https://user-images.githubusercontent.com/23136737/36682986-ba4702d0-1b1c-11e8-993a-2fd4ffa09c49.png)

**Comment by rlguy** [comment]
Hey AlbinSjoegren,

This looks like a problem with your Blender install rather than an error related to the addon. If you uninstall the addon and try to change the seem, does the error still occur? If it does, then the error is unrelated to the addon.

You may try installing Blender 2.78 to see if you still get the error. If the error persists, you may have to try contacting the Blender developers to resolve this.

**Comment by AlbinSjoegren** [comment]
Thanks @rlguy it works with 2.78
