### ISSUE TITLE
[Feature Request] Convert Simulation to Mesh

### ISSUE THREAD

**Issue by rikere** [rlguy/Blender-FLIP-Fluids-Beta#162]
For some project, we just want to use the fluid simulation as a step to getting the final result. For example, if I'm working on a still render with water, I might use the simulation to get started, but then I'll want to change things, maybe delete some parts of the mesh that had splashed up. It's a bit of an edge-case, but it'd be handy to be able to convert the simulation to an editable mesh like we can with the integrated fluid and particle sims.

**Comment by rlguy** [comment]
For a still mesh, I think the best way to do this is to duplicate the surface mesh (eg ctrl+c, ctrl+v) into a separate object so that you can edit the object within Blender. Is this suitable for your workflow?

This will not work well for animation however, because the mesh files with edits will not be written back to the cache directory.

**Comment by rikere** [comment]
Yes, I didn't think I could copy it. I had thought the copy would keep
getting updated. Should add that as a note in documentation as it's
different from other blender stuff where you just click "convert."

**Comment by rlguy** [comment]
Good suggestion! I have added some notes on the cache objects here: https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Object-Settings
