### ISSUE TITLE
Error, Animated meshes must have the same number of vertices for each frame. (Fracture Addon)

### ISSUE THREAD

**Issue by Mitsuma** [rlguy/Blender-FLIP-Fluids-Beta#173]
![blender_2018-02-28_10-08-21](https://user-images.githubusercontent.com/8568089/36779174-6fc55c30-1c6f-11e8-8cc0-b19b6fb9a494.png)

Just found a weird limitation with a certain setting in the Fracture addon.
When you make use of the Fracture Deformation options in combination with the Autohide, Automerge and Perform Merge setting you get this error above.
It is caused because the fracture simulation will automatically add/remove geometry with those settings enabled which apparently is not allowed for exported animated meshes.

I'm not exactly sure how I can work around this at the moment.
![blender_2018-02-28_10-13-40](https://user-images.githubusercontent.com/8568089/36779367-1483970a-1c70-11e8-98e4-901757dd27a7.png)
Scene setup is supposed to be a pipe that gets dented and then bursts open. I need those settings to make it look like bend metal instead of breaking concrete.

Not tested but I could probably convert the fracture simulation to keyframed objects to get around it but I rather not so I can still modify it on the fly which usually works pretty well on with FLIP fluid in my other test.
**Edit:** Actually just tried that, the conversion to keyframed objects will break as well with those things enabled.

**Edit2:** I actually just noticed that I probably don't even need to have "animated" checked on the fractured object. Will report back in a bit.
Will report back in a few hours on this, due to my pipe setup the simulation seems to love to clip through it requiring higher substeps and resolution. It was clipping in a weird way, so I'm not fully sure if that was just the problem.

**Comment by Mitsuma** [comment]
The Fluid seems to ignore the deformation without "animated" checked.
![blender_2018-02-28_23-11-36](https://user-images.githubusercontent.com/8568089/36815993-d5cdd74c-1cdc-11e8-9615-302735750dd7.png)

**Comment by rlguy** [comment]
Hey, this is working as intended. The error is reporting that your mesh has been detected to have changing topology (changing vertices or faces between frames). The simulator is not able to handle meshes with changing topology since it cannot calculate the object velocity. 

I know that the fracture modifier generates meshes with changing topology when using the autohide feature. Fractured objects will need to have the 'Export animated mesh' option checked. Obstacles with motion more complex than keyframed location/rotation/scale will need to have this option enabled.

I am not too experienced with all of the Fracture Modifier features, so I'm not sure of a workaround. Would it work to use separate fracture objects for simulation and render? A fracture without changing topology for the simulation, and a fracture with autohide/automerge feature for rendering?

@dafassi may know how to workaround this issue.

**Comment by Mitsuma** [comment]
I thought about "overlaying" the bend pipe, problem with that is just that without using any of the features it just creates way too many holes, so the fluid simulation will leak everywhere.

![blender_2018-02-28_23-37-41](https://user-images.githubusercontent.com/8568089/36817152-713075a2-1ce0-11e8-85c6-62077c4692e9.png)
I will see if this is enough so it doesn't go everywhere, picture above is without any of those features, maybe the expand option can reduce the holes.

**Comment by rlguy** [comment]
Yes, I would suggest increasing the expand parameter to prevent leaks.

**Comment by Mitsuma** [comment]
Applying the stuff when the bake is done seems to work just fine.  
![blender_2018-03-01_03-36-36](https://user-images.githubusercontent.com/8568089/36824292-d49119dc-1d01-11e8-9ccb-873418de7641.png)

Guess that works as a workaround, although it might not be recommended if one goes for something very precise, might create too much difference in the merged and unmerged version in some cases.

**Comment by rlguy** [comment]
Glad to see this working, aside from a few leaks! Very cool simulation idea!

**Comment by dafassi** [comment]
Sorry for the late answer.
You did right. Autohide and mergin are post features. I would always bake fracture simulation first.
