### ISSUE TITLE
[Discussion] Hardware utilization seems low

### ISSUE THREAD

**Issue by ocheret** [rlguy/Blender-FLIP-Fluids-Beta#180]
When running test cases it doesn't seem like the software is taking advantage of my hardware very well. I decided to check when the fan on my system wasn't ramping up as it does when I run my own compute intensive code.  Task manager shows fairly low utilization numbers...
<img width="579" alt="taskmanagerbycpu" src="https://user-images.githubusercontent.com/1679324/36908550-8cb61316-1e09-11e8-8dfb-20663c2b71e8.PNG">

And it also shows that only 1 of my GPUs is being used at all and even that is not being taxed very much.

<img width="580" alt="taskmanagerperformance" src="https://user-images.githubusercontent.com/1679324/36908585-a30d9850-1e09-11e8-8cf9-cf3bb72e8e90.PNG">

Maybe this is unique to the test cases.

I'm going to download the actual plug-in now and start playing around.

**Comment by rlguy** [comment]
Check out these topics for an explanation:
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal

https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-gpu-usage-is-very-low-is-this-normal

Only one GPU will be used. Due to the type of calculations run on the GPU, it is not beneficial to spread the work across multiple GPUs at the moment.

We have been noticing through test cases that the simulator has been running on the slow side for users with many threads (AMD Threadripper, Intel Xeon hardware). One of the goals for the second wave of invites was to focus on Xeon/AMD hardware and collect test results so that we can better optimize the simulator for this type of hardware.

Let me know if you have any questions/suggestions!

**Comment by ocheret** [comment]
Interesting. I have noticed as the baking has progressed that the GPU utilization has oscillated a bit and has gone as high as 24%. I often do HPC for a living (though never on Windows). I'm guessing Amdahl's law is kicking in or contention for resources across threads (conservative locking) is hurting the CPU multi-threading performance. If you're synchronizing on a key central data structure (e.g. a grid), you might want to partition the grid (a la OpenVDB) or implement some other lock-free discipline. Of course, I have no idea what you're doing under the covers so take what I'm saying with a grain of salt.

**Comment by rlguy** [comment]
Thanks for the input! Most the major calculations do not require synchronized access to a data structure. At the moment, my hypothesis is that there is a large performance penalty from bad memory access patterns in some of the simulation stages. I'm looking at reorganizing/preprocessing data for more sequential or more localized access for improving cache coherency. There is one stage of the simulation that often accounts for 20-30% of the runtime that is pretty much accessing accessing memory randomly. It's a section of the code I've been really meaning to re-evaluate. Partitioning a grid into separate 'subgrid' sections and sorting operations so that they only operate on a single section of the grid is one solution I've wanted to try. I just need to find some time to test out some ideas and see what works.

**Comment by rlguy** [comment]
I'll be closing this discussion to clean up the issue tracker!

**Comment by novacrazy** [comment]
Has there been any update on this?

I also have a 1950X Threadripper and FLIP Fluids just flat out doesn't seem to use more than a couple threads at most. 4-7% CPU utilization on average. GPU acceleration doesn't actually seem to use any GPU, as well. If it does, it's so small that playing a youtube video dwarfs it.

As a result, relatively simple simulations over just 250 frames have estimated simulation times of days.

**Comment by rlguy** [comment]
See this issue: #346

An explanation for CPU and GPU usage is located here:
https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal

https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#my-gpu-usage-is-very-low-is-this-normal

During the beta, we collected data on systems containing CPUs with many cores/threads. Users saw performance increases by lowering the number of threads (in the Advanced Panel), such as by half.

As for long baking times, here are some tips that may help: the time to bake a simulation is proportional to the domain grid size and the number of fluid particles. To reduce the number of fluid particles, you will need to decrease simulation resolution, but this will lose detail. An alternative is to use less fluid, but this may not be possible in the effect you are looking to achieve. 

The simulator runs many calculations on a grid and must process calculations throughout the entire domain grid. If there is a lot of empty space in the grid, this will add to simulation time. So it is best to use a tight-fitting domain that is just large enough to capture the fluid effect.

Hope this adds useful information about performance!

\- Ryan
