### ISSUE TITLE
[Test Case Results] jengo

### ISSUE THREAD

**Issue by jengo** [rlguy/Blender-FLIP-Fluids-Beta#196]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1792619/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1792620/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1792621/test_case_viscous_net65.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1792622/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks jengo!

I checked your results and it looks like the tests ran okay, but you are affected by issue #7. The engine chose to use your integrated graphics chip instead of one of your cards. This issue has been fixed and will be included in the next version!

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
