### ISSUE TITLE
Animating Fluid Velocity

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#208]
When I use an In Flow object, I can animate the Fluid Velocity field, but when using a Fluid object, it errors when I try animate the Fluid Velocity.

"initial_velocity" property cannot be animated

**Comment by rlguy** [comment]
Hey k1ff,

The error happened because the _initial_velocity_ property is set not to be animatable in the addon. If you right click on the property, there is no option to set keyframes. BUT if you use the hotkey _**i**_ to insert a keyframe, that error will be displayed.

Anyway, there is no reason why this property cannot be animated, so I've removed this restriction. This change will be included in the next version (**0.1.3b**).
