### ISSUE TITLE
Previously cached simulation re-opens in fresh Blender session

### ISSUE THREAD

**Issue by RemiGraphics** [rlguy/Blender-FLIP-Fluids-Beta#215]
Not sure if this has been addressed yet. It seems to be a pretty obvious issue, but I haven't seen anything about it.

Yesterday, to begin experimenting with the beta, I made a very basic domain/inflow simulation. I baked it, previewed it, then exited out of Blender without saving. Upon opening a new session of Blender today, adding a domain object, and accidentally hitting play, it played the cached simulation from the night before. The only difference is that it was way bigger than normal. 

The solution was easily fixable, I just had to reset the bake. But this seems like an important issue, if it hasn't already been addressed. 

Keep up the great work on this fantastic add-on! It's really amazing what you guys have done so far.

**Comment by rlguy** [comment]
Thanks for pointing this out! This is because unsaved scenes always use the same default cache directory. I am wondering what your expected/ideal behaviour for this would be:

- Each unsaved scene would use a unique cache directory
- Unsaved .blend files will delete their cache directory on exit
- The previous cache directory would still be loaded, but meshes will be loaded to fit into the new domain object

Let me know if you have any other suggestions!

**Comment by RemiGraphics** [comment]
I figured it was that. Personally, I'd prefer it in unsaved .blend files would delete their cache on exit, similar to how the current fluid simulation system works.

**Comment by rlguy** [comment]
The addon will now delete the cache when closing an unsaved .blend file! This will be included in the next version (**0.1.3b**) which should be available by March 31st.
