### ISSUE TITLE
[Feature Request] General UI Tweaks

### ISSUE THREAD

**Issue by RemiGraphics** [rlguy/Blender-FLIP-Fluids-Beta#227]
After using the add-on on a pretty regular basis, I'd like to propose a few UI changes that I believe may improve the add-on.

1) Replace "Baking in progress... X%" with the amount of baked frames of the total, for example: "Baking in progress... 100/250". Everything in Blender seems to work on a frame basis instead of percentages.
2) Add estimated time remaining into the "FLIP Fluid Simulation Panel" under the Bake/Reset Button. This is a really useful feature, but it's kinda hidden away in the current UI.
3) Show particle counts in "FLIP Fluid Stats" for FLIP, tracer, drop, bubbles, foam, etc.
4) Make the default Debug "Display Grid" colors darker/less saturated. By default, they're so bright they're distracting. This one is nit-picky, but it still would be nice!

Cheers!

**Comment by Mitsuma** [comment]
Want to give my input on those.

1. I would propose to have both maybe. Although you do have the Fluid Stats window that tells you exactly what frame it is at, so this might not need a change at all.

2. You can always pull the panel up, so that it is directly under the first one. 
Like: https://i.imgur.com/XOOmB5s.png
Although I have no idea how I can make that order by default.

3. Nothing to say on this. Could be useful I guess.

4. You can probably easily change that yourself, not tested but the colors are in 
`scripts\addons\bl_flip_fluids\presets\preset_library\sys\default.preset`
![notepad _2018-03-30_03-30-30](https://user-images.githubusercontent.com/8568089/38120703-bb994564-33ca-11e8-8ebf-0498473f456d.png)
Might need somebody more knowledgeable to see if you can just change them, can't test that at the moment.

**Comment by PGTBoos** [comment]
Funny i was thinking just the same, % is not as clear as finished X frames (showing both is best).

**Comment by rlguy** [comment]
I think these are some great suggestions! Easy modifications to make too!

**Comment by rlguy** [comment]
These tweaks have been made and will be included in the next version (**0.1.4b**)!
