### ISSUE TITLE
[Feature Request] Randomize particle sizes for meshing

### ISSUE THREAD

**Issue by PGTBoos** [rlguy/Blender-FLIP-Fluids-Beta#254]
Not a native Englishmen, but I try my best to explain this, 

First of let me be clear that i like this Addon, its just that i see some room for improvements.

On a liquid only simulation, fluid from a distance looks quite good, upon close however it does not look that realistic. The reason for this is all the small (single cell ?) particles, they all have the same size.

So I'd like to suggest a small improvement, have such particles randomly shrink to a random smaller size.
As if in a real world they would randomly evaporate a little. I know this might sound like anti-realism, as small drops don't shrink in real life. But I guarantee that if this shrinking goes slowly over say x frames, then we won't be able to see it is shrinking. (x can be low), however, we would endup width a liquid mesh where the smallest particles are not the same everywhere. And that's more like in nature, and despite is less physical 'property' realistic, in the end, it would look more natural.

such 3dfx might sound strange (destroying volume)  but for an artist/studio it's more important to get a good looking end result then it is to exactly mimic volumes.

It might even be possible also do this for multi-grid-cell objects so not all ripples on it look the same, (with some statistics its possible to still get flat surfaces, but thats maybe something for a next step).

**Comment by rlguy** [comment]
Hey PGTBoos,

Your English is fine and you explained well!

A note on the simulation method: This simulator uses the FLIP simulation method. In the simulation method, the particles actually have no size. The particles are just infinitely small points. Particle sizes are only used when generating the mesh. This means that if we change the particle size, there would be no effect on the physics simulation, which means that there actually wouldn't be a problem with volume conservation. This is good.

Unfortunately, there would be some technical problems with this change though. The meshing process is optimized with the assumption that all particles are the same size. If particles are changed to have varying size, there would be a large performance penalty. Meshing is calculated on the GPU and if we changed the code so particles could have different particle sizes, this would be very very very slow to run on the GPU. We would need to instead run the calculation the CPU, which runs slow. 

_Tip: you can compare GPU/CPU meshing performance by unchecking the **GPU Scalar Field** option in the [FLIP Fluid Advanced](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Advanced-Settings) panel_

This feature could be added as an option, but I'm hesitant to implement this right now. It would require a large code change and I do not want to make changes this large before release since it risks introducing bugs. I'll be closing this issue, but if in the future if this feature becomes more possible, I will reopen it.

**Comment by PGTBoos** [comment]
How about a post process, count connected faces and shrink if < x faces
@home my GPU broke, but 8core CPU still does work fine,

**Comment by rlguy** [comment]
This is a clever solution, but would be quite complex to implement. It is easy to track particles between frames, but difficult to track mesh pieces between frames. Without tracking mesh pieces, we wouldn't be able to set an amount of shrinking that is consistent between frames. Tracking mesh pieces has difficulties such as handling when mesh pieces break off and merge in the simulation. Another difficulty is that meshing takes place on a grid and as particles move through the grid, their generated mesh pieces have quite a variation in the number of faces.

**Comment by PGTBoos** [comment]
I once wrote a customized blob filter in C#, not sure if your familiar width how they work,
But there is a key ingredient to that kind of math that goes like this 
start on a vertex, give it a number, give its neighbors the same ID number, and keep a sum of total vertexes width this ID (in a dictionary key-value => a key and list or array pair), if you got a mesh without a neighbor you assign it a different ID and also sum all those ID's , if you have a vertex joining 2 known ID's you can sum the lower ID to the larger one and notice in a dictionary that the lower ID is no longer a key, but a value of a larger key ID (this time the array or list grows, place lower ID as an extra item in the value side). Eventually, you end up width a dictionary summing all surface sizes per loose object.

Now you dont have to worry where particles are or where the grid is, simply filter by ID to get the smaller objects, for those objects shrink by their center  (center can be collected also in when adding size sum), and shrink it a bit.

i'm though not at all into python, i can only explain about such programming logic in general for other languages. These are moment i wish i was into python, but i lack the time (mostly C# sometimes C++, and a few other languages)
