### ISSUE TITLE
Surface defects

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids-Beta#264]
How to get rid of defects in object fluid_surface?
![01](https://user-images.githubusercontent.com/7983249/38455646-9b1da2ac-3a83-11e8-892f-9f58cb9c0560.jpg)
Modifier Smooth does not help.
The Smoothing Factor and Smoothing Repeat parameters do not help either.

**Comment by rlguy** [comment]
Hey,

The simulator creates a mesh by converting fluid particles into a triangle mesh. Since fluid particles are round, and sometimes jittered around depending on the simulation, there can be defects like this. Unfortunately, some defects are unavoidable and are just a part of working with the fluid simulator. I find that once an animation is rendered, the defects are much less noticeable. 

Usually the smooth modifier helps with this for me. Would you be able to attach the .blend file for me to test and and to see your exact settings?

**Comment by PavelBlend** [comment]
[surface_defects.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1887080/surface_defects.zip)

**Comment by rlguy** [comment]
Increasing the surface _Particle Scale_ can help reduce defects. In general, it is not recommended to set the particle scale to less than 1.0. Here is the surface with a particle scale of 1.3:

![defects1](https://user-images.githubusercontent.com/4285191/38464053-ddd06d22-3abb-11e8-8744-fcbad1b3240d.jpg)

Here is the same, but with a smooth modifier with 1.0 factor and 20 iterations:

![defects2](https://user-images.githubusercontent.com/4285191/38464059-f07845e4-3abb-11e8-84a8-fc39dfbcfa04.jpg)

Increasing the simulation resolution can also help with defects. Here is a resolution of 150 and the same 1.3 particle scale and no smoothing:

![defects3](https://user-images.githubusercontent.com/4285191/38464074-282fde52-3abc-11e8-9b78-27b408f1f5a4.jpg)

Hope this helps!
