### ISSUE TITLE
Missing script file bl_flip_fluids_test_suite in non test version

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#39]
Hi,

Missing script file bl_flip_fluids_test_suite warning when installing the non-test version of FLIP fluids right now

**Comment by rlguy** [comment]
Hey RevDR,

This is caused by how Blender's user preferences work. You will need to save your user settings after uninstalling the addon. If not saved, the next time that Blender loads, it will see that the addon is enabled but the addon does not exist anymore and a warning will be displayed.

I have updated the [Addon Installation and Uninstallation](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Addon-Installation-and-Uninstallation) wiki page to include the _Save User Preferences_ instruction step.
