### ISSUE TITLE
Interface - option to enable fluid whitewater

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#42]
Hi,

This is probably very subjective - but was wondering if the option to enable the fluid whitewater should be higher up in the UI than the display settings for it.  

As the option to use white water controls whether display setting is accessible (i.e. greyed out),  it seems to be more intuitive (to me) to have that option first.

Just a thought.

**Comment by GCharb** [comment]
You can rearrange the UI by clicking and dragging the dots at the right of the box.

![drag_ui](https://user-images.githubusercontent.com/36242050/36265900-3cda1350-123e-11e8-8dab-0c46e0cc740d.gif)

**Comment by RevDr** [comment]
Ah yes - good call - thanks.

I do wonder if the default order should be different so that items higher up affect ones lower down.  However, I realise it might only be me that thinks that.  8-)

**Comment by GCharb** [comment]
You can set Blender in a way that the whitewater option is at the top by default, just follow these steps...

Open Blender
Create a cube
Add the flip fluid from the physics panel
Set the type as domain
Drag the flip fluid whitewater where you want it to be
Delete the cube
Press CTRL + U, click on save startup file

Now the flip fluid whitewater should be where you placed it next time you apply flip fluid domain to an object.

**Comment by RevDr** [comment]
Yup I understand - thanks.

I am simply raising which order the default initial layout should be to make as easy as possible for people on first use.

**Comment by rlguy** [comment]
Cool tip, GCharb! I did not know you could save a default ordering of panels ^^

I agree that if the default ordering of panels is left as-is, it could be confusing for a first-time user to see options related to whitewater display settings before they know how to enable whitewater settings in a lower panel. I also think that the display settings panel should be left where it is high up in the interface because it is an important panel.

What I will do is make the information icon (i) clickable (or perhaps change to a question icon (?)). This will display a menu prompt with text to display something like 'Enable Whitewater Generation'. When clicked, the whitewater generation settings will be enabled.

![enable_whitewater](https://user-images.githubusercontent.com/4285191/36278556-0ddd7136-1249-11e8-9edb-0d48d8f3ada1.jpg)

**Comment by RevDr** [comment]
Sounds a good solution.

**Comment by GCharb** [comment]
Blender interface is quite flexible, but you need to know the little tricks because they are not mentioned in the manual most of the time, comes with years of tinkering with the software!

**Comment by rlguy** [comment]
> What I will do is make the information icon (i) clickable (or perhaps change to a question icon (?)). This will display a menu prompt with text to display something like 'Enable Whitewater Generation'. When clicked, the whitewater generation settings will be enabled.

This has been added and will be included in the next version (0.1.2b).

**Comment by RevDr** [comment]
Ok – fab.

Good fun playing with all this!
