### ISSUE TITLE
Rigid fluid

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#43]
Hi,

Firstly should say I am really loving playing with this - it just so happens I have the week off work which has enabled me plenty of playtime!  Sorry I keep sending so many reports!

This could simply  be how the solver works but in simple example below (images) where
Domain dimensions are: 8 X 8 X 8
And Fluid is 8 X 8 X 2 
With as you can see an initial Z displacement so the water drops as block

The water lands as a solid rigid block and has very little motion when it reaches the bottom.

However, if I reduce the size of my water block to 7 X 7 X 2 - it works as expected.  See other image below.

Thanks

Rigid.... 8 X 8 X 2
![bug4a](https://user-images.githubusercontent.com/36420510/36254193-185abd78-1242-11e8-9dba-68bc791ee461.JPG)

Working 7 X 7 X 2
![bug4b](https://user-images.githubusercontent.com/36420510/36254207-2a066892-1242-11e8-8425-8a77f85d9488.JPG)

**Comment by GCharb** [comment]
I replicated it and I get the same results.

**Comment by rlguy** [comment]
Hey RevDr,

The solver is working as expected physically. When the fluid object drops, only downward velocities are generated. Since the fluid is tight against the domain sides, when it hits the bottom, there is no where for the fluid to move into, so it stops. No sideways velocities are able to be generated to create an interesting splash. 

In real life, the fluid would not stop immediately. There would be inconsistencies that cause velocities other than downwards. Such as wall friction and air resistance. But in the simulator, the initial fluid conditions are all uniform and consistent, and everything takes place in a vacuum.

Hope this makes sense!
