### ISSUE TITLE
Flip Fluid Surface settings don't seem to do anything

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#45]
Hi,

Been trying to play with the FLIP Fluid Surface settings.  However the two parameters I have been changing - subdivisions and smoothing factor - seem to have no effect.

Thanks

**Comment by RevDr** [comment]
...unless these are applied during the bake?  I was kind of presuming they were settings which effected the render mesh post bake.   

So here is a little thought - maybe there needs to be a way to distinguish between

sim settings (effect bake)
mesh settings (post bake - if this is the case)
render settings

Thanks

**Comment by GCharb** [comment]
Yes, these are computed at bake time, smooth makes things look blobby, while increasing subdivision and decreasing particle scale will create higher resolution mesh, but will take longer to calculate.

**Comment by RevDr** [comment]
Does subdivision and smooth do anything different internally that adding the appropriate modifier won't do (other than of course it is baked ?)

**Comment by rlguy** [comment]
Many of the domain settings must be set before baking to take effect. I have opened issue #50 to add documentation for which settings these are.

> Does subdivision and smooth do anything different internally that adding the appropriate modifier won't do (other than of course it is baked ?)

Subdivision is different from Blender's subdivision modifier. Setting the domain subdivision higher will generate mesh data at a higher lever of detail internally within the simulation.

The smoothing settings are essentially the same as what the Blender smooth modifier does. The default settings are fine for most cases to remove blockyness and grid artifacts that come from the raw mesh created by the mesh generator. I'd suggest if you want to add more smoothing, you do so through the Blender smooth modifier since these settings can be modified after baking.

**Comment by RevDr** [comment]
Hi,
Firstly - sorry to reply here - not sure if the protocol is to reply to a closed thread or reopen an old one on a related issue.  So let me know if you prefer the other way round.

Is there anyway to add a feature reprocess a sim with different subdiv/smoothing paramaters post bake (i.e. without repeating whole sim).  I am in the middle of a 12 hour sim - and would prefer not to rerun it if all the information is still available to reprocess for different subdiv settings  Indeed maybe there is an interim bake files that could (optionally) be stored whilst these values are changed and then optionally removed later.  Then again maybe they would be too big to store.



Just a thought.

**Comment by rlguy** [comment]
This is a feature that I plan to add in the future. Meshing/remeshing after simulation will require saving fluid particles for each frame. These files can be quite large depending on size of the simulation (12 bytes per particle), so it will depend on whether the user wants to use the disk space.

Meshing after baking also has some performance advantages. It is possible to mesh multiple frames simultaneously, so users with many threads (Intel Xeon hardware) and large amounts of memory will benefit from this.
