### ISSUE TITLE
Simulations to Alembic?

### ISSUE THREAD

**Issue by niklassjogren** [rlguy/Blender-FLIP-Fluids-Beta#47]
Hi! I read that "_Simulations can be baked to Alembic caches for export to other DCC software, although Guy says that this is currently slow for large caches._", I wanted to try but I do not succeed, just get the first and only one frame and not the animation (Cache)?

/Niklas

**Comment by rlguy** [comment]
Hey Niklas,

There is a workaround to get this working. For Blender to recognise the meshes for Alembic export, you must add a modifier to the mesh object (_fluid_surface_, and if enabled _whitewater_foam, whitewate_bubble, whitewater_spray_). I add a modifier that does nothing such as a smooth modifier with 0 iterations. After adding modifiers, the Alembic cache can be exported with **_File > Export > Alembic_**

I have attached an example of a short Alembic .abc fluid cache (zipped)
[alembic_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1729511/alembic_test.zip)

In the future, the interface will include Alembic export settings to do this automatically. What I would really like to do is have the Alembic library code directly in the fluid engine so that alembic export could be performed faster. This would also allow velocity data to be attached to the mesh which could possibly be used to allow for fluid motion blur rendering.

**Comment by niklassjogren** [comment]
Thank you! I will try that workaround and that future sounds great, looking forward to try that...
/Niklas

**Comment by niklassjogren** [comment]
Hi again. I have been trying some more and it did not work as good as I thought!
I have problem importing the whitewater "particles", dont know how they are exported, probably not as particles becuase I have no problem exporting and importing Blenders ordinary particles through Alembic!
I also get alot of random chrashes in another DCC with the whitewater "particles" but thats probably their fault, just wanted to mention it when I saw another thread about Blender rendering and some crashes!

I probably need to wait and see what you are going to do with your Alembic export and its probably not a high priority right now or...

Then I have to say that the plugin works really well so far, easy to use and really powerful, awesome work!
...and I'm back to testing!
/Niklas

**Comment by rlguy** [comment]
Thanks for letting me know about your tests! I have not spent much time testing Alembic export.

Whitewater particles are exported as regular meshes with only vertex positions. The whitewater system uses meshes instead of particle systems because the Blender Python API does not have the needed flexibility  to handle the complex whitewater particle simulation.

I would like the addon to handle Alembic export on its own instead of using the Blender API. This would allow for better control over how the cache is exported.

**Comment by niklassjogren** [comment]
Hi, is there any news about Flip Fluid's own version of Alembic exports, you wrote that you would rather build your own exporter?

love the plug-in, would just be great with some choices if I would like to use multiple programs. :)

/Niklas

**Comment by schroef** [comment]
How are you able to import white water particles actually. You generate all the mesh outside blender, but i wonder how these particles are then imported into blender being them generated outside.

**Comment by rlguy** [comment]
Hello schroef,

During whitewater simulation, the addon exports the whitewater particles as vertex-only meshes. Each vertex in the mesh represents a whitewater particle. During rendering, the addon imports the vertex meshes and duplicates a small icosphere (or optionally a custom object) over each vertex.

So if you export whitewater to Alembic, the meshes will be vertex-only meshes. For rendering the whitewater in an Alembic cache, you will need to manually duplicate the particle object over the vertices. This is simple using the [dupliverts](https://docs.blender.org/manual/en/dev/editors/3dview/object/properties/duplication/dupliverts.html) method. 

\- Ryan
