### ISSUE TITLE
Different material respectively?

### ISSUE THREAD

**Issue by Toudou-Blender** [rlguy/Blender-FLIP-Fluids-Beta#48]
I understand that fluid material depends on the domain setting.
But if user want to use two type of materials to set to different fluid surface respectively which come from different source, is it or will it be possible?
See image below, for example, 
A left fluid come from "fluid" source. A right fluid come from inflow source. I want to set red material to the left, blue material to the right.

![figure](https://user-images.githubusercontent.com/36343687/36277321-e8b67ac0-12d3-11e8-904d-4c2c2dfe64e4.jpg)

**Comment by rlguy** [comment]
Hey Toudou-Blender,

The simulator is not able to support multiple fluids at the moment. Inside the simulator, all of the fluid is the same. Adding functionality for multiple fluids would require quite a lot of complicated changes to the engine that I do not yet know how to do such as how to handle fluid mixing, how to handle the interface between two fluids, how to mesh two separate fluids so that they are renderable.

This would be a very cool feature to have, but it may be much further into the future until I am knowledgeable enough to implement this.

**Comment by Toudou-Blender** [comment]
OK. If it can be possible, it would be really great feature.
I understand what you said.
Thank you!
