### ISSUE TITLE
[Requires Documentation] How to extend simulation time after finishing bake

### ISSUE THREAD

**Issue by Xepher313** [rlguy/Blender-FLIP-Fluids-Beta#61]
I wasn't entirely sure how to put that into words, so uh, sorry about that.

Anyways, it seems that if your simulation finishes (example: end of timeline is set to 250, and 250 frames are baked) you can't extend that without resetting and restarting. It would be nice to be able to simulate more if the timeline is expanded. (Example: 250 frames are baked, but user decides that the sim should be longer. User extends timeline by 100 frames, but currently is required to restart sim from scratch instead of just "resuming" from frame 251.)

Very sorry for the horrible English.

**Comment by rlguy** [comment]
English seems fine to me! 

You can extend the number of frames by increasing the end frame number. Then switching the ‘Bake Export Settings’ mode to ‘Force’ instead of ‘Default’ this will force the addon to re-export the simulation settings data file to update the frame range and the simulator should continue from the last bake frame.

I’ll add some documentation about this.

**Comment by rlguy** [comment]
Documentation notes abut this have been added to the [Domain Simulation Settings](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Simulation-Settings) page.

**Comment by gogobd** [comment]
Hi! I just wanted to add that I managed to extend the frames range by unzipping flipdata.sim, editing the end frame entry in data.json and tne re-zipping it. Thank you for pointing out this easier solution here!
