### ISSUE TITLE
[Test Case Results] tcheng00

### ISSUE THREAD

**Issue by tcheng00** [rlguy/Blender-FLIP-Fluids-Beta#63]
Hi, 

I'm using a AMD RX480 and ran the fluid sim at 125 resolution.  While it did complete successfully, the secondary particles looks incorrect and all over the place.  Please take a look.  Thanks. 
[test_case_lighthouse125_AMD.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733392/test_case_lighthouse125_AMD.zip)

**Comment by rlguy** [comment]
Thanks for letting me know about this, tcheng00. Are you able to send me any screenshots of the particles? Whitewater particle position calculations are run on the GPU, so I suspect this is an error in the GPU code that is causing issues with AMD hardware. This kind of issue has been seen before when testing with different hardware. I'll look into this further.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

Until this issue is fixed, if you are having problems with whitewater in the Beta version, I would suggest turning off _GPU Particle Advection_ in the _FLIP Fluid Advanced_ settings panel.

**Comment by tcheng00** [comment]
I rendered out an opengl preview of the effect and attached it here. 
[LightHouseTest_foam0000-0500.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1734212/LightHouseTest_foam0000-0500.zip)

Thanks for the test build.

**Comment by GCharb** [comment]
Dang, that looks messed up, it simulated and rendered fine here, I will try on my laptop with an AMD card, see if I get the same results!

Here is a render simulated with my GTX 960.
![lighthouse2](https://user-images.githubusercontent.com/36242050/36393731-c61fff60-157e-11e8-8d17-d93355f102fb.png)

**Comment by rlguy** [comment]
Thanks for the video, that definitely does not look right! Another tester reported a similar issue with whitewater generation who is also using the same AMD GPU model (AMD RX480). I'll be closing this issue and moving the discussion to this issue: #78

**Comment by tcheng00** [comment]
Cool.  My GTX 960 does work fine too.  I'll check the other thread.
