### ISSUE TITLE
Fluid 'baking' but not displaying when "inverse" is selected on an obstacle?

### ISSUE THREAD

**Issue by camcam2015** [rlguy/Blender-FLIP-Fluids-Beta#69]
I don't know if there's a setting I'm missing or that isn't documented that prevents this behavior. In the scene below it bakes normally on default settings and displays in the viewport. When I enable the "inverse" object on the obstacle it "bakes", but it is calculated way faster than normal and the sim result doesn't show up in the viewport.

![blender_2018-02-18_13-03-35](https://user-images.githubusercontent.com/16390086/36355109-25e049f6-14ac-11e8-80bb-918cb8be4356.png)

I wanted to apply the inverse setting to the object below and the same thing seems to occur. I've tried adding/applying a solidify modifier and flipping the normals of the object both ways.

![blender_2018-02-18_13-11-25](https://user-images.githubusercontent.com/16390086/36355151-3efd5108-14ad-11e8-9d74-03a0bdd6f2e5.png)

**Comment by rlguy** [comment]
Hey camcam2015,

In the documentation on the [inverse setting](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Obstacle-Object-Settings):

> Inverse
> Turn the object 'inside-out' within the simulation. The inside of the object will become hollow while the outside will become solid.

In your first example, enabling inverse on the sphere will turn the entire domain solid except for a hollow empty space where the sphere is. I assume the object above the sphere is fluid/inflow. Since the rest of the domain except the sphere is now solid, fluid cannot be created in the simulation and that is why it is processing very fast and no fluid is showing up.

I'm not sure how your second mesh is designed, but you might want to check out this documentation on [manifold meshes](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Manifold-Meshes) to make sure your meshes will work correctly with the simulator. This documentation is currently in progress and is not yet linked to the obstacle documentation page.

Hope this clears things up! Let me know if you have any questions.

**Comment by camcam2015** [comment]
Ah that makes sense! I may have just misunderstood what the docs were trying to convey, I fixed the issue.
