### ISSUE TITLE
Viscosity setting

### ISSUE THREAD

**Issue by Toudou-Blender** [rlguy/Blender-FLIP-Fluids-Beta#81]
I have set the viscosity value to 0.0001 as below.
![image2](https://user-images.githubusercontent.com/36343687/36407315-fceaefec-1640-11e8-8e4e-9d3b1b8b996b.jpg)

After that, it displays 0.000 as below.
![image1](https://user-images.githubusercontent.com/36343687/36407336-2d4e60ba-1641-11e8-8b6d-bab347c51e6f.jpg)

Clicking the text field of the viscosity again, the value shows "0.0001".
I don't know that it is efficient value less than 0.001. But if it works, displaying the viscosity value should not show 0.000, I think. Can you increase number of digits to show whole value?

And can you add a preset of viscosity of various materials using physical unit such as Pa*s?
(Reference : https://en.wikipedia.org/wiki/Viscosity#Other_substances)

**Comment by rlguy** [comment]
Hey Toudou-Blender,

**Viscosity Setting**

This is just the way that Blender handles number fields. There isn’t a way to dynamically show more digits if the number is small. Blender will store your exact number, but will cut off the last digits for display.

I will be leaving this setting set to 3 digits since lower viscosity values aren’t really effective at smaller values.

**Viscosity Presets**

The viscosity value in this simulator doesn’t relate to a real life physical quantity. So if you copy a real life viscosity value into the simulator, it may not match the visual thickness of the real life liquid.

We are experimenting with viscosity presets by matching video footage to simulation values. This won’t be a comprehensive list of presets like the tables you linked to, but it will give you an idea of what viscosity values to use for different liquids.

Tip: when experimenting, try values in the range of 0 to 10. If you want thicker, then you can try values up to around 100.

***

Hope this answers your question! Let me know if you have any other questions.

**Comment by Toudou-Blender** [comment]
OK. I understand.
Thank you!
