### ISSUE TITLE
Performance differences between 2 computers

### ISSUE THREAD

**Issue by niklassjogren** [rlguy/Blender-FLIP-Fluids-Beta#85]
Hi.
I see big differences in how much resources my computers use when I do an simulation? I have tried to have the same settings in Blender and it is the same scene (cascading_water_feature-lite.blend) i tried now but I see differences on all scenes!
My Desktop uses 30-40% CPU and 0.5-1% GPU.
My Laptop uses 70-90% CPU and 30-35% GPU.
Is there a reason or could it be an error? If there is a bug, what should I try and what would you like to know?
![performance_usage](https://user-images.githubusercontent.com/7673361/36446286-24a3f016-1681-11e8-9c77-2dd046e07958.jpg)
/Niklas

**Comment by rlguy** [comment]
Hey niklassjogren!

This is a good question. In general, laptops have less computational resources than a desktop and the simulator is able to use proportionally more CPU/GPU resources on a laptop.

I checked your specs and your desktop has 12 threads available and your laptop has 4 threads available. It's easier for the simulator to use 4 threads at a high load rather than 12 threads at a high load. This is because fluid simulation is very memory heavy problem and memory access is slow compared to how fast your CPU is. On your Desktop, 12 threads are all trying to access a large amount of memory at the same time and more memory accesses will lead to lower CPU usage. On your laptop, you have only 4 threads making memory accesses and this allows the CPU to spend usage on computing rather than fetching memory.

The above is the same for GPU usage, except instead of threads you have compute units and instead of RAM you have VRAM. But on a GPU, memory accesses are much much much slower.

One thing you can experiment with is with changing the number of threads in the [FLIP Fluid Advanced](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Advanced-Settings) panel. Ony our desktop I would try comparing running a simulation with 6 threads and comparing the timing for a simulation with 12 threads. Depending on your hardware setup it could be possible that running a lower number a threads will process the simulation faster. I would be curious about the results if you do try this.

Hope this clears some things up! Let me know if you have any questions.

**Comment by niklassjogren** [comment]
Thanks for the explanation, very interesting technical info!
Did some quick tests with threads. Looked like all 12 threads are used, more or less, on all tests?
Got some results but this was a simple scene, maybe it's a difference if I'm increasing the resolution alot:
![desktop_threads_cache_info](https://user-images.githubusercontent.com/7673361/36450287-af3eb18c-168d-11e8-884d-a2c3e9171818.jpg)
/Niklas

**Comment by rlguy** [comment]
Thanks for the info! In general, the CPU usage will increase when testing at a higher resolution. I have added some documentation on what was discussed in this issue explaining CPU usage [here](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal).
